version: "3"
services:
  ledgerproxy: 
    image: haproxy-ledger-dev-img
    container_name: haproxy_ledger_dev_cont
    hostname: ${HOSTNAME}
    build:
      context: .
      dockerfile: ./lb/Dockerfile.ledger.lb
    volumes:
      - ./certs:/certs
    ports: 
      - '443:443'
    networks:
      client_network:
      ledger_network:
    depends_on:
      - ledger
  ledger:
    image: ledger-img
    build:
      context: .
      dockerfile: ./ledger/Dockerfile
    ports:
      - '1098'
    environment:
      - NODE_ENV=docker
      - NODE_OPTIONS="--max-old-space-size=4096"
    volumes:
      - ledger-data:/usr/src/simpleledger
    networks:
      ledger_network:
      ledger_db_layer:
    healthcheck:
      test: curl --fail http://localhost:1098/poll || kill 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
networks:
  client_network:
    driver: bridge
  ledger_network:
    driver: bridge
  ledger_db_layer:
    driver: bridge
volumes:
  ledger-data: